# رفع الذاكرة لـ 4 جيجا لتناسب معالجة ملفات الـ TFLite و C++
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8

# تفعيل الخصائص الحديثة لأندرويد
android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableJetifier=true

# تحسين أداء البناء العملياتي
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true
android.disableAutomaticComponentCreation=true
android.applicationid=android
