pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url = uri("https://chaquo.com/maven") }
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url = uri("https://chaquo.com/maven") }
        maven { url = uri("https://jitpack.io") } // 🛠️ تم تعديل الصيغة هنا لتتوافق مع Kotlin DSL
    }
}
rootProject.name = "Aegis-Tactical-Master"
include(":app")
