plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.jamesfirstok.aegis' 
    compileSdk 34

    defaultConfig {
        applicationId "com.jamesfirstok.aegis"
        minSdk 24
        targetSdk 34
        versionCode 8
        versionName "1.0.8-Sovereign-Master"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        
        externalNativeBuild {
            cmake {
                cppFlags "-std=c++17"
                // تحسين المعالجة لمعماريات ARM المتطورة
                abiFilters "armeabi-v7a", "arm64-v8a"
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled true 
            // تفعيل حماية الأكواد لمنع الهندسة العكسية
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
            version "3.22.1"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    buildFeatures {
        viewBinding true
    }
}

dependencies {
    // المكتبات الأساسية
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    
    // محركات الذكاء الاصطناعي والرصد التكتيكي
    implementation 'org.tensorflow:tensorflow-lite:2.12.0'
    implementation 'org.mavlink:mavlink-sdk:2.4.1'
    
    // الاتصالات والارتباط الفضائي
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.google.android.gms:play-services-maps:18.2.0'
    
    // أدوات الحماية والتشفير
    implementation "androidx.security:security-crypto:1.1.0-alpha06"
}
